trafficanno/trafficanno/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
]

trafficanno/user/urls.py
from django.contrib.auth.views import PasswordResetDoneView
from django.urls import path

from .views import AdvertiserRegistration, PublisherRegistration, Registration, EmailSubmitting, PasswordSubmit, Login, \
    ForgotPassword, MyPasswordResetConfirmView, AdvertProfile, PublProfile, PublFormProfile, RessetPass, \
    AdvertFormProfile, logout_view

urlpatterns = [
    path('sign-up/advertiser/', AdvertiserRegistration.as_view(), name='advert-reg'),
    path('sign-up/publisher/', PublisherRegistration.as_view(), name='pub-reg'),
    path('sign-up/', Registration.as_view(),  name='sign-up'),
    path('sign-up/email_submit', EmailSubmitting.as_view(), name='email_submit'),
    path('sign-up/password_confirm' , PasswordSubmit.as_view(), name='password_submit'),
    path('login/', Login.as_view(), name='login'),
    path('forgot_password/', ForgotPassword.as_view(), name="forgot_password"),

    path('reset_confirm/<uidb64>/<token>/',MyPasswordResetConfirmView.as_view(template_name='user/confirmation.html'),name='confirmation'),
    path('submit_password/<uidb64>/<token>/',PasswordSubmit.as_view(), name='password_confirm'),

    path('password-reset/complete/', PasswordResetDoneView.as_view(template_name='user/complete.html'),name='password_reset_complete'),
    path('advert-profile', AdvertProfile.as_view() , name="advert_profile"),
    path('publ-profile', PublProfile.as_view() , name="publ_profile"),
    path('publ_profile_form' , PublFormProfile.as_view(), name= "publ_profile_form"),
    path('advert_profile_form', AdvertFormProfile.as_view(), name="advert_profile_form"),
    path('reset_pass', RessetPass.as_view() , name='reset_pass'),
    path('logout/', logout_view, name='logout'),

]

trafficanno/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify


class User(AbstractUser):
    username = models.CharField(max_length=50, verbose_name='First Name', unique=False)
    country_of_residence = models.CharField(max_length=350,
                                            verbose_name='Country of residence')
    city = models.CharField(max_length=230, verbose_name='City')
    address = models.CharField(max_length=400, verbose_name='Address')
    email = models.EmailField(unique=True, verbose_name='Email')
    messenger_choices = [('Skype', 'Skype'), ('Telegram', "Telegram")]
    messenger = models.CharField(max_length=50, choices=messenger_choices, blank=True, null=False)
    messenger_nickname = models.CharField(max_length=270, verbose_name='Messenger nickname')
    is_advertiser = models.BooleanField(default=False, verbose_name='Is advertiser?')
    is_publisher = models.BooleanField(default=False, verbose_name='Is publisher?')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def save(self, *args, **kwargs):
        self.username = slugify(self.first_name)
        return super(User, self).save(*args, **kwargs)


class AdvertiserAccount(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key=True,
                                verbose_name='User',
                                related_name='advertiser')
    short_desc = models.TextField(max_length=5000,
                                  verbose_name='Advertising campaign short description')
    bonus_code = models.CharField(max_length=350, verbose_name='Bonus code')
    balance = models.DecimalField(default=0, max_digits=8, decimal_places=2)

    class Meta:
        verbose_name = 'advertiser'
        verbose_name_plural = 'Advertisers'

    def __str__(self):
        return f'User: {self.user}'


class PublisherAccount(models.Model):
    TRAFFIC_AMOUNT = (
        (1, '<5k daily'),
        (2, '5-10k daily'),
        (3, '>10k daily')
    )
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key=True,
                                verbose_name='User',
                                related_name='publisher')
    website = models.TextField(max_length=5000,
                               verbose_name='Website')
    traffic_amount = models.PositiveSmallIntegerField(choices=TRAFFIC_AMOUNT,
                                                      verbose_name='Daily traffic amount')

    total_income = models.DecimalField(default=0, decimal_places=2, max_digits=8)
    available_payout = models.DecimalField(default=0, decimal_places=2, max_digits=8)
    usdt_trc = models.CharField(max_length=40, blank=True, null=True)
    custom = models.CharField(max_length=60, blank=True, null=True)
    wire_swift = models.CharField(max_length=50, blank=True, null=True)
    wire_comments = models.CharField(max_length=100, blank=True, null=True)
    bank_name = models.CharField(max_length=50, blank=True, null=True)
    bank_address = models.CharField(max_length=40, blank=True, null=True)
    bank_country = models.CharField(max_length=15, blank=True, null=True)
    account_number = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = 'publisher'
        verbose_name_plural = 'Publishers'

    def __str__(self):
        return f'User: {self.user}'

trafficanno/user/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm, \
    PasswordChangeForm
from django.db import transaction
from .models import AdvertiserAccount, PublisherAccount
from django.forms import ValidationError
from django.utils.translation import gettext, gettext_lazy as _

User = get_user_model()


class AdvertiserSignUpForm(UserCreationForm):
    short_desc = forms.CharField(label='Short description of your advertising campaign',
                                 widget=forms.Textarea(attrs={'class': 'form-control',
                                                               'rows': 3}))
    bonus_code = forms.CharField(label='Bonus code',
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    agree_privacy = forms.BooleanField(
        label='I agree with my data processing and i accept Terms & Conditions and Privacy policy', required=True)
    receive_newsletter = forms.BooleanField(
        label='I agree to recieve special offers,financial,techinical and other helpful information', required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'country_of_residence', 'city',
                  'address', 'email', 'messenger', 'messenger_nickname', 'short_desc',
                  'bonus_code')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'country_of_residence': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'messenger': forms.Select(attrs={'class': 'form-control'}),
            'messenger_nickname': forms.TextInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(AdvertiserSignUpForm, self).__init__(*args, **kwargs)
        del self.fields['password1']
        del self.fields['password2']

    def clean(self):
        self.cleaned_data['password1'] = 'Passoerdq213123f'
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('This email address is already in use.')
        return email

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_advertiser = True
        user.set_unusable_password()
        user.save()

        try:
            AdvertiserAccount.objects.create(user=user,
                                             short_desc=self.cleaned_data['short_desc'],
                                             bonus_code=self.cleaned_data['bonus_code'])
        except (Exception,):
            raise ValidationError('When creating advertiser account, something went wrong')

        return user


class PublisherSignUpForm(UserCreationForm):
    website = forms.CharField(label='Website',
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    traffic_amount = forms.ChoiceField(choices=PublisherAccount.TRAFFIC_AMOUNT,
                                       label='Daily traffic amount',
                                       widget=forms.Select(attrs={'class': 'form-control'}))
    agree_privacy = forms.BooleanField(
        label='I agree with my data processing and i accept Terms & Conditions and Privacy policy', required=True)
    receive_newsletter = forms.BooleanField(
        label='I agree to recieve special offers,financial,techinical and other helpful information', required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'country_of_residence', 'city',
                  'address', 'email', 'messenger', 'messenger_nickname',)
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'country_of_residence': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'messenger': forms.Select(attrs={'class': 'form-control'}),
            'messenger_nickname': forms.TextInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(PublisherSignUpForm, self).__init__(*args, **kwargs)
        del self.fields['password1']
        del self.fields['password2']

    def clean(self):
        self.cleaned_data['password1'] = 'Passoerdq2asdasdajsdjaidj13123f'
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('This email address is already in use.')
        return email

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_publisher = True
        user.set_unusable_password()
        user.save()

        try:
            PublisherAccount.objects.create(user=user,
                                            website=self.cleaned_data['website'],
                                            traffic_amount=self.cleaned_data['traffic_amount'])
        except (Exception,):
            raise ValidationError('When creating advertiser account, something went wrong')

        return user


class PasswordConfirm(forms.Form):
    new_password1 = forms.CharField(
        label=_("Set Password"),
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )
    new_password2 = forms.CharField(
        label=_("Confirm Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data


class EmailAuthenticationForm(AuthenticationForm):
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'autocomplete': 'email'}))
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'password'}))


class ForgotPasswordForm(PasswordResetForm):
    email = forms.EmailField(label="Email",
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'autocomplete': 'email'}))


class ResetSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password",
                                          "class": "form-control"}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password",
                                          "class": "form-control"}),
    )


class PublProfileForm(forms.ModelForm):
    website = forms.CharField(label='Website',
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    traffic_amount = forms.ChoiceField(choices=PublisherAccount.TRAFFIC_AMOUNT,
                                       label='Daily traffic amount',
                                       widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'country_of_residence', 'city',
                  'address', 'email', 'messenger', 'messenger_nickname',)
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'disabled': True}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'disabled': True}),
            'country_of_residence': forms.TextInput(attrs={'class': 'form-control', 'disabled': True}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'disabled': True}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'disabled': True}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'disabled': True}),
            'messenger': forms.TextInput(attrs={'class': 'form-control'}),
            'messenger_nickname': forms.TextInput(attrs={'class': 'form-control'})

        }


class AdvertProfileForm(forms.ModelForm):
    short_desc = forms.CharField(label='Short description of your advertising campaign',
                                 widget=forms.TextInput(attrs={'class': 'form-control',
                                                               'rows': 3, 'disabled': True}))
    bonus_code = forms.CharField(label='Bonus code',
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'country_of_residence', 'city',
                  'address', 'email', 'messenger', 'messenger_nickname', 'short_desc',
                  'bonus_code')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'disabled': True}),

trafficanno/user/templates/user/user_inc/vertical_nav/advert_add_funds.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Add funds</h2>
    <hr>
    <form>
  <label>
    <input type="radio" name="payment" value="paypal">
    PayPal
  </label>
  <br>
  <label>
    <input type="radio" name="payment" value="wireusd">
    Wire USD
  </label>
  <br>
  <label>
    <input type="radio" name="payment" value="bankcard">
    Bank Card
  </label>
  <br>
  <label>
    <input type="radio" name="payment" value="bankcard">
    WebMoney EUR
  </label>
  <br>
  <label>
    <input type="radio" name="payment" value="bankcard">
    Paxum
  </label>
   <br>
 <button type="submit" class="btn btn-primary">Proceed</button>
</form>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/advert_campaigns.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Campaigns</h1>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/advert_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Dashboard</h1>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/advert_finance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Finance</h1>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/advert_news_offers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Learn more</a>
  </div>
</div>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/advert_support.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Support</h1>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/advert_tracking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Tracking</h1>
    <h3>Select a conversion tracker or a CPA network.</h3>
    <div class="picture-container">
  <div class="picture" onclick="handleClick(1)">
    <img src="templates/media/binom.png">
  </div>
  <div class="picture" onclick="handleClick(2)">
    <img src="picture2.jpg">
  </div>
  <div class="picture" onclick="handleClick(3)">
    <img src="picture3.jpg">
  </div>
  <div class="picture" onclick="handleClick(4)">
    <img src="picture4.jpg">
  </div>
  <div class="picture" onclick="handleClick(5)">
    <img src="picture5.jpg">
  </div>
  <div class="picture" onclick="handleClick(6)">
    <img src="picture6.jpg">
  </div>
  <div class="picture" onclick="handleClick(7)">
    <img src="picture7.jpg">
  </div>
  <div class="picture" onclick="handleClick(8)">
    <img src="picture8.jpg">
  </div>
  <div class="picture" onclick="handleClick(9)">
    <img src="picture9.jpg">
  </div>
  <div class="picture" onclick="handleClick(10)">
    <img src="picture10.jpg">
  </div>
</div>
    <h3>Click 'Copy' to get your postback URL.</h3>
    <input type="text" id="urlInput" value="https://example.com" readonly>
    <button type="submit" class="btn btn-primary" onclick="copyToClipboard()">Copy URL</button>
    <h3>Paste your postback URL to the 'Traffic Source' settings of your tracking solution or CPA network.</h3>

    <script>
      function copyToClipboard() {
        var urlInput = document.getElementById("urlInput");
        urlInput.select();
        document.execCommand("copy");
        alert("URL copied to clipboard!");
      }
    </script>

<style>
  .picture-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

.picture {
  margin: 10px;
  border: 1px solid black;
  cursor: pointer;
}

.picture img {
  max-width: 100%;
}
</style>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/advert_traffic_inventory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Traffic inventory</h1>
    <p>This tool calculates the daily traffic amount available according to the campaign settings, and selected targeting options.</p>
    <p>The data is based on yesterday's traffic performance.</p>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="push-notifications-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Push-notifications</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="instant-text-message-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Instant Text Message</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="video-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Video</button>
      </li>
        <li class="nav-item" role="presentation">
        <button class="nav-link" id="banner-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Banner</button>
      </li>
        <li class="nav-item" role="presentation">
        <button class="nav-link" id="onclick-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">OnClick(Popunder)</button>
      </li>
        <li class="nav-item" role="presentation">
        <button class="nav-link" id="skim-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Skim</button>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="push-notifications" role="tabpanel" aria-labelledby="push-notifications-tab">...</div>
      <div class="tab-pane fade" id="instant-text-message" role="tabpanel" aria-labelledby="instant-text-message-tab">...</div>
      <div class="tab-pane fade" id="video" role="tabpanel" aria-labelledby="video-tab">...</div>
      <div class="tab-pane fade" id="banner" role="tabpanel" aria-labelledby="banner-tab">...</div>
      <div class="tab-pane fade" id="onclick" role="tabpanel" aria-labelledby="onclick-tab">...</div>
      <div class="tab-pane fade" id="skim" role="tabpanel" aria-labelledby="skim-tab">...</div>
    </div>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/publ_api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>dsaddasda</h1>

</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/publ_dashboard.html
<!DOCTYPE html>
<html>
<head>
  <title>Line Chart Example</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>

<label for="today">Today's Date:</label>
	<input type="text" id="today" name="today" readonly>

	<script>
		// get today's date
		var today = new Date();

		// format date as "Month Day, Year" (e.g. "March 31, 2023")
		var options = { year: 'numeric', month: 'long', day: 'numeric' };
		var formatted_date = today.toLocaleDateString('en-US', options);

		// set value of input field to today's date
		document.getElementById("today").value = formatted_date;
	</script>
  <canvas id="line-chart"></canvas>

  <script>
    var ctx = document.getElementById('line-chart').getContext('2d');

    var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        datasets: [
          {
            label: 'Profits',
            yAxisID: 'left-y-axis',
            data: [200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300],
            borderColor: 'blue',
            fill: false
          },
          {
            label: 'Impressions',
            yAxisID: 'right-y-axis',
            data: [10000, 12000, 15000, 20000, 22000, 24000, 26000, 28000, 30000, 32000, 35000, 40000],
            borderColor: 'red',
            fill: false
          }
        ]
      },
      options: {
        responsive: true,
        title: {
          display: true,
          text: 'Monthly Profits and Impressions'
        },
        legend: {
          position: 'bottom'
        },
        scales: {
          xAxes: [{
            scaleLabel: {
              display: true,
              labelString: 'Month'
            }
          }],
          yAxes: [
            {
              id: 'left-y-axis',
              position: 'left',
              scaleLabel: {
                display: true,
                labelString: 'Profits ($)'
              }
            },
            {
              id: 'right-y-axis',
              position: 'right',
              scaleLabel: {
                display: true,
                labelString: 'Impressions'
              }
            }
          ]
        }
      }
    });
  </script>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/publ_nav_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



    <h3><b>THETER (USDT) TRC20 EUR</b></h3>
    <p>Wallet number: {{ request.user.publisher.usdt_trc }}</p>
    <hr>
    <h3><b>CUSTOM</b></h3>
    <p>account number: {{ request.user.publisher.custom }}</p>
    <hr>
    <h3><b>Wire USD</b></h3>
    <p>Swift: {{ request.user.publisher.wire_swift }}</p>
    <p>Comments: {{ request.user.publisher.wire_comments }}</p>
    <p>Bank name: {{ request.user.publisher.bank_name }}</p>
    <p>Bank address: {{ request.user.publisher.bank_address }}</p>
    <p>Bank country: {{ request.user.publisher.bank_country }}</p>
    <p>Account number: {{ request.user.publisher.account_number }}</p>
    <hr>

    <form action="{% url 'publ_profile_form' %}" method="post" style="margin-bottom: 50px">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
    <h3>Resset Password</h3>
    <div class="success-message" style="color: #8ff352;">

    </div>
    <form action="{% url 'reset_pass' %}" class="pass_change_form" method="post" style="margin-bottom: 50px">
    {% csrf_token %}
    {{ form_pass.non_field_errors }}

    <div class="form-group">
        <label for="id_old_password">Old password:</label>
        {{ form_pass.old_password }}
        <div class="invalid-feedback" style="display: block">

        </div>
    </div>

    <div class="form-group">
        <label for="id_new_password1">New password:</label>
        {{ form_pass.new_password1 }}
        <div class="invalid-feedback" style="display:block;">

        </div>
    </div>

    <div class="form-group">
        <label for="id_new_password2">New password confirmation:</label>
        {{ form_pass.new_password2 }}
        <div class="invalid-feedback" style="display: block">

        </div>
    </div>

    <button type="submit" class="btn btn-primary">Reset Password</button>
</form>





</body>

trafficanno/user/templates/user/user_inc/vertical_nav/publ_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>AHAHAHAHHA</h1>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/publ_payments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
		nav {
			background-color: #333;
			overflow: hidden;
		}

		nav a {
			float: left;
			color: white;
			text-align: center;
			padding: 14px 16px;
			text-decoration: none;
			font-size: 17px;
		}

		nav a:hover {
			background-color: #ddd;
			color: black;
		}

		table {
			border-collapse: collapse;
			width: 100%;
			max-width: 800px;
			margin: 0 auto;
		}

		th, td {
			text-align: left;
			padding: 8px;
		}

		th {
			background-color: #333;
			color: white;
		}

		tr:nth-child(even) {
			background-color: #f2f2f2;
		}
	</style>
</head>
</head>
<body>
<nav>
		<a href="#payments" onclick="toggleTable('payments')">Payments</a>
		<a href="#earnings" onclick="toggleTable('earnings')">Earnings</a>
	</nav>

	<table id="payments">
		<thead>
			<tr>
				<th>Payment Date</th>
				<th>Amount</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>01/01/2023</td>
				<td>$100.00</td>
				<td>Completed</td>
			</tr>
			<tr>
				<td>02/01/2023</td>
				<td>$50.00</td>
				<td>Completed</td>
			</tr>
			<tr>
				<td>03/01/2023</td>
				<td>$75.00</td>
				<td>Processing</td>
			</tr>
		</tbody>
	</table>

	<table id="earnings">
		<thead>
			<tr>
				<th>Month</th>
				<th>Amount</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>January</td>
				<td>$500.00</td>
			</tr>
			<tr>
				<td>February</td>
				<td>$750.00</td>
			</tr>
			<tr>
				<td>March</td>
				<td>$1000.00</td>
			</tr>
		</tbody>
	</table>

	<script>
		function toggleTable(id) {
			var table = document.getElementById(id);
			if (table.style.display === 'none') {
				table.style.display = 'table';
			} else {
				table.style.display = 'none';
			}
		}
	</script>
</body>
</html>

trafficanno/user/templates/user/user_inc/vertical_nav/publ_statistics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Ads Today</h1>
<h1>Ads this month</h1>
<h1>Forecast of March 2023</h1>
</body>
</html>